package io.mosip.testrig.dslrig.dataprovider.util;

public enum ResidentAttribute {
	RA_PRIMARAY_LANG,
	RA_SECONDARY_LANG,
	RA_THIRD_LANG,
	RA_FirstName,
	RA_LastName,
	RA_Country,
	RA_State,
	RA_City,
	RA_Age,
	RA_Infant,
	RA_Minor,
	RA_Adult,
	RA_Senior,
	RA_Gender,
	RA_Phone,
	RA_Photo,				
	RA_Iris,				
	RA_Finger,				
	RA_Document,
	RA_DocumentCategory,
	RA_FingersList,			
	RA_SKipGaurdian,		
	RA_InvalidList,
	RA_MissList,
	RA_SCHEMA_VERSION,
	RA_LargeFace,
	RA_ObstructedFace,
	RA_LowQualityDocument
}
